name: Deploy to Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_TEST }}
        run: |
          npm run build
          # Add deployment steps specific to your hosting platform for the test environment
